名称: 与上游同步

开启:
计划:
→ 每周三和周日零点运行  
工作流调度:      # 允许手动触发

作业:
  sync:
    runs-on: ubuntu-latest
    steps:
      - 名称: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史
          
      - name: 配置git
        run: |
          git config --global user.name "Antchen123"
          git config --global user.email "antchen123456@outlook.com"
          
      - 名称: 添加上游仓库
: git 远程添加上游 https://github.com/KuekHaoYang/KVideo.git
        
      - 名称: 获取上游更改
运行: git 获取上游
        
      - name: 合并上游更改
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          
      - name: Push changes to origin
        run: git push origin main
